# Generated by Django 3.2 on 2024-02-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0003_immunogen_record_schedule_vaccine_timing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recordview',
            name='record',
        ),
        migrations.RemoveField(
            model_name='recordview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='record',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='user',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='vaccine_type',
        ),
        migrations.RemoveField(
            model_name='timing',
            name='schedule_done',
        ),
        migrations.RemoveField(
            model_name='vaccinationschedule',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='imu_id',
        ),
        migrations.DeleteModel(
            name='Immunogen',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='RecordView',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Timing',
        ),
        migrations.DeleteModel(
            name='VaccinationSchedule',
        ),
        migrations.DeleteModel(
            name='Vaccine',
        ),
    ]
