# Generated by Django 3.2 on 2024-02-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0004_auto_20240208_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_healthcare_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Child', 'Child'), ('Doctor', 'Doctor'), ('Healthcare Provider', 'Healthcare Provider')], default='Child', max_length=50),
        ),
    ]
