# Generated by Django 3.2 on 2024-02-17 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0006_auto_20240211_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vaccine.healthcareprovider'),
        ),
    ]
