# Generated by Django 3.2 on 2024-02-18 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0008_auto_20240217_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthcareprovider',
            old_name='contact_number',
            new_name='phone',
        ),
    ]
