# Generated by Django 3.2 on 2024-02-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0011_birthdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdetails',
            name='user',
        ),
    ]
