# Generated by Django 3.2 on 2024-02-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0014_auto_20240219_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Child', 'Child'), ('Doctor', 'Doctor'), ('HealthcareProvider', 'HealthcareProvider')], default='Child', max_length=50),
        ),
    ]
