# Generated by Django 3.2 on 2024-02-21 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0015_alter_customuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BirthDetails',
        ),
    ]
