# Generated by Django 3.2 on 2024-02-21 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0019_birthdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BirthDetails',
        ),
    ]
