# Generated by Django 3.2 on 2024-02-21 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0020_delete_birthdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.FloatField(blank=True, max_length=100, null=True)),
                ('height', models.FloatField(blank=True, max_length=100, null=True)),
                ('regno', models.CharField(blank=True, max_length=50, null=True)),
                ('rchid', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
