# Generated by Django 3.2 on 2024-02-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0021_birthdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BirthDetails',
        ),
    ]
