# Generated by Django 3.2 on 2024-02-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0026_vaccine_vaccinepurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='edition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='edition_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='last_updated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
