# Generated by Django 3.2 on 2024-03-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0043_vaccine_vaccinepurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
