# Generated by Django 3.2 on 2024-03-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0045_alter_vaccine_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
    ]
