# Generated by Django 4.2.5 on 2024-03-06 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0053_company_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinepurchase',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='vaccinepurchase',
            name='vaccine',
        ),
        migrations.DeleteModel(
            name='Vaccine',
        ),
        migrations.DeleteModel(
            name='VaccinePurchase',
        ),
    ]
