# Generated by Django 4.2.5 on 2024-03-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0055_vaccine_vaccinepurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_company',
            field=models.BooleanField(default=True),
        ),
    ]
