# Generated by Django 4.2.5 on 2024-03-20 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0058_alter_customuser_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BirthDetails',
        ),
    ]
