# Generated by Django 4.2.5 on 2024-03-20 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0063_alter_birthdetails_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BirthDetails',
        ),
    ]
