# Generated by Django 4.2.5 on 2024-03-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0066_vaccinationschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationschedule',
            name='notification_sent',
        ),
    ]
