# Generated by Django 4.2.5 on 2024-03-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0068_vaccinationslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VaccinationSlot',
        ),
    ]
