# Generated by Django 4.2.5 on 2024-03-29 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0070_vaccinationslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VaccinationSlot',
        ),
    ]
