# Generated by Django 4.2.5 on 2024-03-30 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0072_slot_vaccinationslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationslot',
            name='child',
        ),
        migrations.RemoveField(
            model_name='vaccinationslot',
            name='slot',
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
        migrations.DeleteModel(
            name='VaccinationSlot',
        ),
    ]
