# Generated by Django 4.2.5 on 2024-04-04 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0075_vaccinationslot_recipient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='child_appointments', to='vaccine.birthdetails'),
        ),
    ]
