# Generated by Django 4.2.5 on 2024-04-04 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0077_vaccineprescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccineprescription',
            name='vaccine_name',
        ),
        migrations.AddField(
            model_name='vaccineprescription',
            name='vaccine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='vaccine.vaccine'),
        ),
        migrations.AlterField(
            model_name='vaccineprescription',
            name='appointment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_prescription', to='vaccine.appointment'),
        ),
        migrations.AlterField(
            model_name='vaccineprescription',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_prescriptions', to='vaccine.doctor'),
        ),
        migrations.AlterField(
            model_name='vaccineprescription',
            name='doses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
