# Generated by Django 4.2.5 on 2024-04-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0078_remove_vaccineprescription_vaccine_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccineprescription',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
