# Generated by Django 4.2.5 on 2024-04-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0079_alter_vaccineprescription_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccineprescription',
            name='doses',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
