# Generated by Django 4.2.5 on 2024-04-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0080_alter_vaccineprescription_doses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccineprescription',
            name='vaccine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='vaccine.vaccine'),
        ),
    ]
