# Generated by Django 4.2.5 on 2024-04-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0081_alter_vaccineprescription_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccineprescription',
            name='doses',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
