# Generated by Django 4.2.5 on 2024-04-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0084_alter_vaccineprescription_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='vaccine',
        ),
        migrations.RemoveField(
            model_name='checkoutitem',
            name='vaccine',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='vaccine',
        ),
        migrations.RemoveField(
            model_name='vaccinationslot',
            name='vaccine',
        ),
        migrations.RemoveField(
            model_name='vaccineprescription',
            name='vaccine',
        ),
        migrations.RemoveField(
            model_name='vaccinepurchase',
            name='vaccine',
        ),
        migrations.DeleteModel(
            name='Vaccine',
        ),
    ]
