# Generated by Django 4.2.5 on 2024-04-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0085_remove_cartitem_vaccine_remove_checkoutitem_vaccine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('edition_date', models.DateField(blank=True, null=True)),
                ('edition_status', models.CharField(blank=True, max_length=200, null=True)),
                ('last_updated_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
