# Generated by Django 4.2.5 on 2024-04-05 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0086_vaccine'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='vaccine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccine'),
        ),
        migrations.AddField(
            model_name='checkoutitem',
            name='vaccine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccine'),
        ),
        migrations.AddField(
            model_name='payment',
            name='vaccine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccine'),
        ),
        migrations.AddField(
            model_name='vaccinationslot',
            name='vaccine',
            field=models.CharField(choices=[('BCG', 'BCG'), ('OPV', 'OPV'), ('HEB B', 'HEB B'), ('DPT', 'DPT'), ('IPV', 'IPV'), ('MEASLES', 'Measles'), ('VITAMIN A', 'Vitamin A'), ('JE', 'JE'), ('OPV BOOSTER', 'OPV Booster'), ('DDT BOOSTER', 'DDT Booster'), ('DPT BOOSTER', 'DPT Booster'), ('TT', 'TT(Tetanus Toxoid)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vaccineprescription',
            name='vaccine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='vaccine.vaccine'),
        ),
        migrations.AddField(
            model_name='vaccinepurchase',
            name='vaccine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccine'),
        ),
    ]
