# Generated by Django 4.2.5 on 2024-04-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0087_cartitem_vaccine_checkoutitem_vaccine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationslot',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vaccinationslot',
            name='slot',
            field=models.TimeField(),
        ),
    ]
