# Generated by Django 4.2.5 on 2024-04-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0088_vaccinationslot_is_booked_alter_vaccinationslot_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationslot',
            name='slot',
            field=models.CharField(choices=[('10:00 AM', '10:00 AM'), ('11:00 AM', '11:00 AM'), ('12:00 PM', '12:00 PM'), ('01:00 PM', '01:00 PM'), ('02:00 PM', '02:00 PM'), ('03:00 PM', '03:00 PM')], max_length=20),
        ),
    ]
