# Generated by Django 4.2.5 on 2024-04-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0089_alter_vaccinationslot_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationslot',
            name='slot',
            field=models.TimeField(),
        ),
    ]
