# Generated by Django 4.2.5 on 2024-04-12 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0093_delete_vaccinationslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('slot', models.TimeField()),
                ('recipient_phone', models.CharField(default='', max_length=20)),
                ('is_booked', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('given', 'Given'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.birthdetails')),
                ('vaccine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='vaccine.vaccine')),
            ],
        ),
    ]
