# Generated by Django 4.2.5 on 2024-04-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0094_vaccinationslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VaccinationSlot',
        ),
    ]
