# Generated by Django 4.2.5 on 2024-04-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0096_vaccinationslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationslot',
            name='vaccine',
            field=models.CharField(choices=[('BCG', 'BCG'), ('OPV', 'OPV'), ('HEB B', 'HEB B'), ('DPT', 'DPT'), ('IPV', 'IPV'), ('MEASLES', 'Measles'), ('VITAMIN A', 'Vitamin A'), ('JE', 'JE'), ('OPV BOOSTER', 'OPV Booster'), ('DDT BOOSTER', 'DDT Booster'), ('DPT BOOSTER', 'DPT Booster'), ('TT', 'TT(Tetanus Toxoid)')], max_length=20, null=True),
        ),
    ]
