# Generated by Django 4.2.5 on 2024-04-12 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0097_alter_vaccinationslot_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationslot',
            name='vaccine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_slots', to='vaccine.vaccine'),
        ),
    ]
