# Generated by Django 4.2.5 on 2024-04-13 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0099_vaccinationslot_birth_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationslot',
            name='birth_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_details', to='vaccine.birthdetails'),
        ),
    ]
