# Generated by Django 4.2.5 on 2024-04-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0101_delete_vaccinationschedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationslot',
            name='vaccine',
        ),
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_months', models.FloatField()),
                ('vaccines', models.ManyToManyField(to='vaccine.vaccine')),
            ],
        ),
    ]
