# Generated by Django 4.2.5 on 2024-04-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0102_remove_vaccinationslot_vaccine_vaccinationschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VaccinationSchedule',
        ),
    ]
