# Generated by Django 4.2.5 on 2024-04-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0103_delete_vaccinationschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('vaccine_name', models.CharField(max_length=100)),
            ],
        ),
    ]
